rp.endpoint = http://localhost:8080
rp.api.key = reportkey_iJJL7kC6Q9iBl1-E3cHIjq6izXyt2iVIP5E4GbDgBBsE_2kplavc89Y9IvTuxBms
rp.launch =  Best_Buy_API_BDD
rp.project = default_personal
log4j.rootLogger=INFO, RP
log4j.appender.RP=com.epam.reportportal.log4j.appender.ReportPortalAppender
log4j.appender.RP.layout=org.apache.log4j.PatternLayout
log4j.appender.RP.layout.ConversionPattern=%d{ABSOLUTE} %-5p [%c{1}] %m%n